#
#
# Автор плагина: CriperMS
#
#
# Плейсхолдеры: %player% - игрок, который находится в данный момент на проверке!
#
# Права (для Luckperms или PermissionsEx):
# cripercheck.check - Вызывать игроков на проверку
# cripercheck.anydesk - Вызывать на проверку через AnyDesk
# cripercheck.mod - Отправлять сообщения модеатору на поверке если у игрока мут (НЕ ЗАБУДЬТЕ ВЫДАТЬ ОБЫЧНЫМ ИГРОКАМ!!)
#
# Комманды:
# /check <Ник Игрока> - Вызвать игрока на проверку
# /check - Отпустить с проверки (работает только во время проверки)
# /anycheck <Ник> - Вызвать на проверку через AnyDesk.
# /anycheck - Отпустить игрока с проверки (работает только во время проверки)
#
#


check_title: "&cПроверка на читы"
check_subtitle: "&fВсе инструкции находятся в чате."
anycheck_title: "&cПРОВЕРКА ЧЕРЕЗ ANYDESK"
anycheck_subtitle: "&fВсе инструкции находятся в чате."


check_chat_messages:
  - ""
  - "&4&lВНИМАНИЕ &7Вы были вызваны на &cПроверку читов"
  - ""
  - "&cПишите свой дискорд ник в чат. &7У вас есть 4 минуты"
  - "&7Если у вас мут используйте &6/mod сообщение"
  - ""
  - "&7Признание в использовании читов - &c'замените на время бана' "
  - "&7За выход с севера во время проверки - &c'замените на время бана'"
  - ""
  - "&7Модератору на проверке &cзапрещено &7скидывать вам различные команды для ПК (powershell, cmd), а так же ссылки на скачивание программ."
  - ""
  - "&7Увидели нарушение со стороны модератора, фиксируйте этом сообщайте нам об этом на форум: &c'форум'"
  - ""
anycheck_chat_messages:
  - "&4&lВНИМАНИЕ &7Вы были вызваны на проверку через &4AnyDesk"
  - ""
  - "&7Инструкция: &c'инструкция'"
  - ""
  - "&cПишите свой код доступа AnyDesk в чат. &7У вас есть 5 минут"
  - "&7Если у вас мут используйте &6/mod сообщение"
  - ""
  - "&7Признание в использовании читов - &c'время бана'"
  - "&7За выход с сервера во время проверки - &c'время'"
  - ""
  - "&7Важно: Проверяющему запрещено вводить различные команды для ПК (powershell, cmd), а так же совершать действия которые не касаются проверки (отвязка аккаунта и тому подобное)."
  - ""
  - "&7Увидели нарушение со стороны модератора, фиксируйте это и сообщайте нам об этом на форум: 'форум'"
  - ""


command_messages:
  not_a_player: "&cТолько игроки могут выполнять эту команду."
  check_usage: "&6Check &7» &6Использование: &7/check <игрок>"
  anycheck_usage: "&cИспользование: /anycheck <игрок>"
  player_not_found: "&6Check &7» &cИгрок не найден."
  moderator_check_start: "&6Check &7» &6Игрок вызван на проверку."
  moderator_check_end: "&6Check &7» &6Проверка завершена."
  no_player_checked: "&6Check &7» &6Используйте /check <игрок>"
  not_in_check: "&6Check &7» &6Вы не на проверке."
  invalid_mod_usage: "&6Check &7» &6Использование: &7/mod <сообщение>"
  mod_offline: "&cМодератор оффлайн."
  only_mod_command: "&6Check &7» &cВы не можете прописывать комманды во время поверки."
  message_sent_confirm: "&7Сообщение отправлено модератору."


message_for_moderator_format: "&6Check &7» &6%player%: &c%message%"


